# Generated by Django 5.1.8 on 2026-05-26 01:33

import django.core.validators
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUIDv7 primary key — time-sortable unique identifier.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp when the record was last modified.', verbose_name='Updated at')),
                ('name', models.CharField(help_text='Human-readable name for this camera.', max_length=255, verbose_name='Name')),
                ('code', models.CharField(db_index=True, help_text='Unique device identifier for this camera.', max_length=64, unique=True, verbose_name='Code')),
                ('model_name', models.CharField(blank=True, help_text='Manufacturer and model name of the camera.', max_length=255, verbose_name='Camera model')),
                ('sensor_type', models.CharField(blank=True, help_text='Image sensor type (e.g. CMOS, CCD).', max_length=128, verbose_name='Sensor type')),
                ('resolution_width', models.PositiveIntegerField(blank=True, help_text='Horizontal resolution in pixels.', null=True, verbose_name='Resolution width (px)')),
                ('resolution_height', models.PositiveIntegerField(blank=True, help_text='Vertical resolution in pixels.', null=True, verbose_name='Resolution height (px)')),
                ('fps', models.PositiveSmallIntegerField(blank=True, help_text='Recording frame rate in frames per second.', null=True, verbose_name='Frame rate (fps)')),
                ('field_of_view_deg', models.DecimalField(blank=True, decimal_places=2, help_text='Diagonal field of view in degrees.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Field of view (°)')),
                ('lens_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Camera lens focal length in millimetres.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Focal length (mm)')),
                ('azimuth_deg', models.DecimalField(blank=True, decimal_places=2, help_text='Azimuth pointing direction in degrees (0 = North, clockwise).', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Azimuth (°)')),
                ('elevation_deg', models.DecimalField(blank=True, decimal_places=2, help_text='Elevation angle in degrees (0 = horizon, 90 = zenith).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Elevation (°)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], db_index=True, default='active', max_length=16, verbose_name='Status')),
                ('installed_at', models.DateField(blank=True, help_text='Date the camera was installed at the station.', null=True, verbose_name='Installation date')),
                ('technical_params', models.JSONField(blank=True, default=dict, help_text='Additional technical parameters as key-value pairs.', verbose_name='Technical parameters')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['station', 'name'],
            },
        ),
    ]
