# Generated by Django 5.1.8 on 2026-05-28 23:28

import secrets

from django.db import migrations, models


def populate_camera_hash_ids(apps, schema_editor):
    """Populate unique hash_id for every existing Camera row."""
    Camera = apps.get_model("camera", "Camera")
    for camera in Camera.objects.filter(hash_id=""):
        camera.hash_id = secrets.token_hex(12)
        camera.save(update_fields=["hash_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0002_initial"),
    ]

    operations = [
        # Step 1 – add the column as non-unique with an empty default
        migrations.AddField(
            model_name="camera",
            name="hash_id",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Short unique identifier used in script configuration files.",
                max_length=32,
                verbose_name="Hash ID",
            ),
            preserve_default=False,
        ),
        # Step 2 – fill in unique values for any pre-existing rows
        migrations.RunPython(populate_camera_hash_ids, migrations.RunPython.noop),
        # Step 3 – add the unique constraint
        migrations.AlterField(
            model_name="camera",
            name="hash_id",
            field=models.CharField(
                default="",
                editable=False,
                help_text="Short unique identifier used in script configuration files.",
                max_length=32,
                unique=True,
                verbose_name="Hash ID",
            ),
        ),
    ]
