# Generated by Django 5.1.8 on 2026-05-29 00:07

import sky_events.apps.camera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camera", "0003_hash_ids_and_script_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="camera_type",
            field=models.CharField(
                choices=[("fixed", "Fixed"), ("allsky", "All-sky"), ("wide", "Wide-angle")],
                db_index=True,
                default="fixed",
                help_text="Type of camera: 'Fixed' points to a specific direction (azimuth/elevation required), 'All-sky' covers the full dome (180 °), 'Wide-angle' covers a broad area without full coverage.",
                max_length=16,
                verbose_name="Camera type",
            ),
        ),
        migrations.AlterField(
            model_name="camera",
            name="hash_id",
            field=models.CharField(
                default=sky_events.apps.camera.models._generate_hash_id,
                editable=False,
                help_text="Short unique identifier used in script configuration files.",
                max_length=32,
                unique=True,
                verbose_name="Hash ID",
            ),
        ),
    ]
