# Generated by Django 5.1.8 on 2026-06-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_camera_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='detector',
            field=models.CharField(choices=[('generic', 'Generic'), ('ufocapture', 'UFOCapture'), ('rms', 'RMS'), ('allskeye', 'AllSkyEye'), ('meteordl', 'MeteorDL'), ('metrec', 'MetRec')], default='generic', help_text='Reporter capture software used by this camera.', max_length=32, verbose_name='Detector'),
        ),
    ]
