# Generated by Django 5.1.8 on 2026-05-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SkyEvents', help_text='Display name of the application.', max_length=100, verbose_name='site name')),
                ('page_title', models.CharField(default='Automated meteor observation network', help_text='Shown in the browser tab and meta description.', max_length=200, verbose_name='page title / tagline')),
                ('hero_badge', models.CharField(default='Meteor detection network', help_text='Short label shown in the badge above the hero title.', max_length=100, verbose_name='hero badge')),
                ('hero_pre_highlight', models.CharField(default='Observe the', max_length=150, verbose_name='hero title — before highlight')),
                ('hero_highlight', models.CharField(default='cosmos', help_text='This word will be rendered with the accent gradient.', max_length=50, verbose_name='hero title — highlighted word')),
                ('hero_post_highlight', models.CharField(default='automatically.', max_length=150, verbose_name='hero title — after highlight')),
                ('hero_subtitle', models.TextField(default='SkyEvents coordinates your network of stations, cameras, and radio receivers to detect and classify astronomical events in real time.', verbose_name='hero subtitle')),
                ('features_eyebrow', models.CharField(default='Platform', max_length=50, verbose_name='features eyebrow')),
                ('features_title', models.CharField(default='Everything your network needs', max_length=200, verbose_name='features section title')),
                ('features_subtitle', models.TextField(default='A unified platform for managing multi-station observation infrastructure and real-time event processing.', verbose_name='features section subtitle')),
                ('stats_stations_label', models.CharField(default='Observation stations', max_length=100, verbose_name='stats: stations label')),
                ('stats_cameras_label', models.CharField(default='Cameras supported', max_length=100, verbose_name='stats: cameras label')),
                ('stats_radios_label', models.CharField(default='Radio receivers', max_length=100, verbose_name='stats: radios label')),
                ('stats_events_label', models.CharField(default='Events detected', max_length=100, verbose_name='stats: events label')),
                ('cta_title', models.CharField(default='Ready to join the network?', max_length=200, verbose_name='CTA title')),
                ('cta_subtitle', models.TextField(default='Sign in to access your dashboard and start monitoring your stations.', verbose_name='CTA subtitle')),
                ('contact_email', models.EmailField(blank=True, default='', help_text='Optional public contact address shown in the footer.', max_length=254, verbose_name='contact e-mail')),
                ('footer_text', models.CharField(blank=True, default='', help_text='Optional extra line displayed at the bottom of the page.', max_length=255, verbose_name='footer text')),
            ],
            options={
                'verbose_name': 'site configuration',
                'verbose_name_plural': 'site configuration',
            },
        ),
    ]
