# Generated by Django 5.1.8 on 2026-05-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0004_fix_hero_bg_style_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_bg_style',
            field=models.CharField(choices=[('grid', 'Grid'), ('dots', 'Dots'), ('stars', 'Stars'), ('meteors', 'Meteors'), ('aurora', 'Aurora'), ('nebula', 'Nebula'), ('christmas', 'Christmas'), ('summer', 'Summer'), ('night', 'Night sky'), ('day', 'Day sky'), ('neon', 'Neon'), ('humo', 'Smoke'), ('startrails', 'Star trails'), ('orbits', 'Orbits'), ('pulse', 'Pulse'), ('wave', 'Wave'), ('geo', 'Geo'), ('void', 'Void'), ('plasma', 'Plasma'), ('rain', 'Rain')], default='grid', help_text='Visual style for the hero section background.', max_length=20, verbose_name='hero background style'),
        ),
    ]
