"""
Abstract base models for SkyEvents.

All domain models should inherit from these base classes to ensure
consistency across the codebase.

Design decisions:
- UUIDs v7 as primary keys: time-sortable, globally unique, no sequential guessing
- created_at / updated_at on every model: essential for audit trails
- All timestamps in UTC: no timezone ambiguity
- soft-delete pattern NOT used at this level (implemented per-model when needed)

@file   sky_events/apps/core/models.py
@author slopez.tech
"""

from __future__ import annotations

import uuid

from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from uuid6 import uuid7


class DeviceStatus(models.TextChoices):
    """
    Generic operational status for observation sites and physical devices.

    Stations are physical observation sites that host one or more cameras
    and/or radio receivers. This status vocabulary is shared across all
    three models so that filtering and display logic can be centralised.
    """

    ACTIVE = "active", _("Active")
    INACTIVE = "inactive", _("Inactive")
    MAINTENANCE = "maintenance", _("Maintenance")


class UUIDModel(models.Model):
    """
    Abstract base model that uses a UUIDv7 primary key.

    UUIDv7 is preferred over UUIDv4 because:
    - It is time-sortable (monotonically increasing)
    - Better index performance in PostgreSQL (less fragmentation)
    - Encodes creation timestamp (useful for debugging)

    @note   The ``id`` field is intentionally NOT auto-generated by the DB;
            the Python layer generates it. This ensures the ID is known
            before the INSERT, which simplifies event sourcing patterns.
    """

    id: models.UUIDField = models.UUIDField(
        primary_key=True,
        default=uuid7,
        editable=False,
        verbose_name="ID",
        help_text="UUIDv7 primary key — time-sortable unique identifier.",
    )

    class Meta:
        abstract = True


class TimeStampedModel(UUIDModel):
    """
    Abstract model that adds ``created_at`` and ``updated_at`` timestamps.

    Both fields are automatically managed:
    - ``created_at`` is set once on creation (``auto_now_add``)
    - ``updated_at`` is updated on every save (``auto_now``)

    All timestamps are stored in UTC.
    """

    created_at: models.DateTimeField = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name="Created at",
        help_text="UTC timestamp when the record was created.",
    )
    updated_at: models.DateTimeField = models.DateTimeField(
        auto_now=True,
        verbose_name="Updated at",
        help_text="UTC timestamp when the record was last modified.",
    )

    class Meta:
        abstract = True
        ordering = ["-created_at"]

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__} id={self.id}>"


class SoftDeleteQuerySet(models.QuerySet["SoftDeleteModel"]):
    """Custom QuerySet that filters out soft-deleted records by default."""

    def alive(self) -> SoftDeleteQuerySet:
        """Return only non-deleted records."""
        return self.filter(deleted_at__isnull=True)

    def deleted(self) -> SoftDeleteQuerySet:
        """Return only soft-deleted records."""
        return self.filter(deleted_at__isnull=False)

    def delete(self) -> tuple[int, dict[str, int]]:
        """Soft-delete all records in the queryset."""
        return self.update(deleted_at=timezone.now()), {}


class SoftDeleteManager(models.Manager["SoftDeleteModel"]):
    """Manager that returns only alive (non-deleted) records by default."""

    def get_queryset(self) -> SoftDeleteQuerySet:
        return SoftDeleteQuerySet(self.model, using=self._db).alive()

    def all_with_deleted(self) -> SoftDeleteQuerySet:
        """Return all records including soft-deleted ones."""
        return SoftDeleteQuerySet(self.model, using=self._db)


class SoftDeleteModel(TimeStampedModel):
    """
    Abstract model that adds soft-delete capability.

    Instead of permanently removing records, this model sets ``deleted_at``.
    The default manager filters out deleted records automatically.

    Use ``Model.objects.all_with_deleted()`` to include deleted records.
    """

    deleted_at: models.DateTimeField = models.DateTimeField(
        null=True,
        blank=True,
        db_index=True,
        verbose_name="Deleted at",
        help_text="UTC timestamp when the record was soft-deleted. NULL if active.",
    )

    objects: SoftDeleteManager = SoftDeleteManager()  # type: ignore[assignment]

    class Meta:
        abstract = True

    @property
    def is_deleted(self) -> bool:
        """Return True if this record has been soft-deleted."""
        return self.deleted_at is not None

    def delete(  # type: ignore[override]
        self,
        using: str | None = None,
        keep_parents: bool = False,
    ) -> tuple[int, dict[str, int]]:
        """Soft-delete this record instead of destroying it."""
        self.deleted_at = timezone.now()
        self.save(update_fields=["deleted_at", "updated_at"])
        return 1, {self.__class__.__name__: 1}

    def hard_delete(self, using: str | None = None, keep_parents: bool = False) -> None:
        """Permanently delete this record from the database."""
        super().delete(using=using, keep_parents=keep_parents)

    def restore(self) -> None:
        """Restore a soft-deleted record."""
        self.deleted_at = None
        self.save(update_fields=["deleted_at", "updated_at"])
