# Generated by Django 5.1.8 on 2026-05-26 04:53

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0002_initial'),
        ('events', '0001_initial'),
        ('radio', '0002_initial'),
        ('station', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationReport',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUIDv7 primary key — time-sortable unique identifier.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp when the record was last modified.', verbose_name='Updated at')),
                ('recorded_at', models.DateTimeField(db_index=True, help_text='UTC timestamp when the device first detected the event.', verbose_name='recorded at (UTC)')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Duration of the detection in milliseconds.', null=True, verbose_name='duration (ms)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('linked', 'Linked to event'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, help_text='Operator notes or automatic processing remarks.', verbose_name='notes')),
                ('camera', models.ForeignKey(blank=True, help_text='Camera that recorded this detection (leave blank for radio-only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='camera.camera', verbose_name='camera')),
                ('event', models.ForeignKey(blank=True, help_text='Astronomical event this report is linked to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='events.astronomicalevent', verbose_name='event')),
                ('radio_receiver', models.ForeignKey(blank=True, help_text='Radio receiver that detected this echo (leave blank for optical-only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='radio.radioreceiver', verbose_name='radio receiver')),
                ('station', models.ForeignKey(help_text='Station that produced this report.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='station.station', verbose_name='station')),
            ],
            options={
                'verbose_name': 'station report',
                'verbose_name_plural': 'station reports',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUIDv7 primary key — time-sortable unique identifier.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp when the record was last modified.', verbose_name='Updated at')),
                ('file_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('spectrogram', 'Spectrogram'), ('audio', 'Audio'), ('data', 'Data file'), ('other', 'Other')], db_index=True, default='video', max_length=20, verbose_name='file type')),
                ('filename', models.CharField(help_text='Original filename or path on the station storage.', max_length=512, verbose_name='filename')),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, help_text='File size in bytes, if known.', null=True, verbose_name='file size (bytes)')),
                ('description', models.CharField(blank=True, help_text='Short description of the file contents.', max_length=255, verbose_name='description')),
                ('is_available', models.BooleanField(default=True, help_text='Whether this file can currently be requested or downloaded.', verbose_name='available')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='reports.stationreport', verbose_name='report')),
            ],
            options={
                'verbose_name': 'report file',
                'verbose_name_plural': 'report files',
                'ordering': ['file_type', 'filename'],
            },
        ),
    ]
