# Generated by Django 5.1.8 on 2026-05-29 00:27

import django.db.models.deletion
import sky_events.apps.reports.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        ("station", "0004_add_media_requirement_and_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="UUIDv7 primary key — time-sortable unique identifier.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="UTC timestamp when the record was created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC timestamp when the record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "requested_paths",
                    models.JSONField(
                        default=list,
                        help_text="List of local file paths on the station to be uploaded.",
                        verbose_name="requested paths",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Admin notes about what these files are needed for.",
                        verbose_name="notes",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional deadline after which the requirement is no longer served to the script.",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_requirements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="requested by",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_requirements",
                        to="station.station",
                        verbose_name="station",
                    ),
                ),
            ],
            options={
                "verbose_name": "media requirement",
                "verbose_name_plural": "media requirements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="UUIDv7 primary key — time-sortable unique identifier.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="UTC timestamp when the record was created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC timestamp when the record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded media file from the station.",
                        upload_to=sky_events.apps.reports.models._attachment_upload_to,
                        verbose_name="file",
                    ),
                ),
                (
                    "original_path",
                    models.CharField(
                        help_text="Local file path on the station storage.",
                        max_length=1024,
                        verbose_name="original path",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("image", "Image"),
                            ("spectrogram", "Spectrogram"),
                            ("audio", "Audio"),
                            ("data", "Data file"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                        verbose_name="file type",
                    ),
                ),
                (
                    "file_size_bytes",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="file size (bytes)"
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="reports.mediarequirement",
                        verbose_name="requirement",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "report attachment",
                "verbose_name_plural": "report attachments",
                "ordering": ["-created_at"],
            },
        ),
    ]
