# Generated by Django 5.1.8 on 2026-06-03 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_add_media_requirement_and_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediarequirement",
            name="report_file",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific report file this requirement is for, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requirements",
                to="reports.reportfile",
                verbose_name="report file",
            ),
        ),
    ]
