# Generated by Django 5.1.8 on 2026-05-26 01:33

import django.core.validators
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioReceiver',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUIDv7 primary key — time-sortable unique identifier.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp when the record was last modified.', verbose_name='Updated at')),
                ('name', models.CharField(help_text='Human-readable name for this radio receiver.', max_length=255, verbose_name='Name')),
                ('code', models.CharField(db_index=True, help_text='Unique device identifier for this radio receiver.', max_length=64, unique=True, verbose_name='Code')),
                ('receiver_model', models.CharField(blank=True, help_text='Manufacturer and model of the radio receiver or SDR dongle.', max_length=255, verbose_name='Receiver model')),
                ('frequency_mhz', models.DecimalField(decimal_places=3, help_text='Reception centre frequency in megahertz (e.g. 143.050 for GRAVES).', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frequency (MHz)')),
                ('bandwidth_khz', models.DecimalField(blank=True, decimal_places=2, help_text='Reception bandwidth in kilohertz.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bandwidth (kHz)')),
                ('antenna_type', models.CharField(blank=True, help_text='Antenna type used for meteor radio detection (e.g. Yagi, dipole).', max_length=128, verbose_name='Antenna type')),
                ('polarization', models.CharField(blank=True, help_text='Antenna polarization (e.g. horizontal, vertical, circular).', max_length=64, verbose_name='Polarization')),
                ('software', models.CharField(blank=True, help_text='Software used for reception and recording (e.g. SDRSharp, GQRX, Spectrum Lab).', max_length=255, verbose_name='Software')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], db_index=True, default='active', max_length=16, verbose_name='Status')),
                ('installed_at', models.DateField(blank=True, help_text='Date the radio receiver was installed at the station.', null=True, verbose_name='Installation date')),
                ('technical_params', models.JSONField(blank=True, default=dict, help_text='Additional technical parameters as key-value pairs.', verbose_name='Technical parameters')),
            ],
            options={
                'verbose_name': 'Radio receiver',
                'verbose_name_plural': 'Radio receivers',
                'ordering': ['station', 'name'],
            },
        ),
    ]
