# Generated by Django 5.1.8 on 2026-05-26 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radio', '0001_initial'),
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioreceiver',
            name='station',
            field=models.ForeignKey(help_text='Station this radio receiver belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='radio_receivers', to='station.station', verbose_name='Station'),
        ),
        migrations.AddIndex(
            model_name='radioreceiver',
            index=models.Index(fields=['station', 'status'], name='radio_station_status_idx'),
        ),
        migrations.AddIndex(
            model_name='radioreceiver',
            index=models.Index(fields=['status'], name='radio_status_idx'),
        ),
        migrations.AddIndex(
            model_name='radioreceiver',
            index=models.Index(fields=['frequency_mhz'], name='radio_frequency_idx'),
        ),
    ]
