# Generated by Django 5.1.8 on 2026-06-03 02:48

import sky_events.apps.radio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_hash_ids_and_script_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioreceiver',
            name='detector',
            field=models.CharField(choices=[('generic', 'Generic'), ('echoes', 'Echoes')], default='generic', help_text='Reporter capture software used by this radio receiver.', max_length=32, verbose_name='Detector'),
        ),
        migrations.AlterField(
            model_name='radioreceiver',
            name='hash_id',
            field=models.CharField(default=sky_events.apps.radio.models._generate_hash_id, editable=False, help_text='Short unique identifier used in script configuration files.', max_length=32, unique=True, verbose_name='Hash ID'),
        ),
    ]
