"""
StationReport and ReportFile models.

Design decisions
----------------
- StationReport is the primary detection record.  It is produced by a single
  station device (camera **or** radio receiver — exactly one should be set,
  but the constraint is soft so incomplete imports can still be saved).
- ``event`` is nullable: a report may arrive before an admin has created the
  corresponding AstronomicalEvent.  Once linked, the report contributes
  measurement data to the event.
- ``recorded_at`` is the device-local UTC timestamp of the detection onset,
  distinct from ``created_at`` (when the record was entered in the system).
- ReportFile stores metadata about data files (video, image, spectrogram, …)
  that exist on the station's storage.  ``is_available`` signals whether
  the file can currently be requested for download / analysis.
- File content is NOT stored in the database — only metadata.  Object
  storage integration (S3 / MinIO) is a future enhancement.

@file   sky_events/apps/reports/models.py
@author slopez.tech
"""

from __future__ import annotations

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from sky_events.apps.camera.models import Camera
from sky_events.apps.core.models import TimeStampedModel
from sky_events.apps.radio.models import RadioReceiver
from sky_events.apps.station.models import Station


class ReportStatus(models.TextChoices):
    PENDING = "pending", _("Pending")
    LINKED = "linked", _("Linked to event")
    ARCHIVED = "archived", _("Archived")


class FileType(models.TextChoices):
    VIDEO = "video", _("Video")
    IMAGE = "image", _("Image")
    SPECTROGRAM = "spectrogram", _("Spectrogram")
    AUDIO = "audio", _("Audio")
    DATA = "data", _("Data file")
    OTHER = "other", _("Other")


class StationReport(TimeStampedModel):
    """
    A single detection record generated by a station device.

    Produced automatically by the station software (or entered manually by
    an operator) and later linked to a confirmed AstronomicalEvent by an
    admin.
    """

    # --- Event association -----------------------------------------------
    event = models.ForeignKey(
        "events.AstronomicalEvent",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reports",
        verbose_name=_("event"),
        help_text=_("Astronomical event this report is linked to."),
    )

    # --- Origin -----------------------------------------------------------
    station = models.ForeignKey(
        Station,
        on_delete=models.CASCADE,
        related_name="reports",
        verbose_name=_("station"),
        help_text=_("Station that produced this report."),
    )
    camera = models.ForeignKey(
        Camera,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reports",
        verbose_name=_("camera"),
        help_text=_("Camera that recorded this detection (leave blank for radio-only)."),
    )
    radio_receiver = models.ForeignKey(
        RadioReceiver,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="reports",
        verbose_name=_("radio receiver"),
        help_text=_("Radio receiver that detected this echo (leave blank for optical-only)."),
    )

    # --- Detection timing -------------------------------------------------
    recorded_at = models.DateTimeField(
        _("recorded at (UTC)"),
        db_index=True,
        help_text=_("UTC timestamp when the device first detected the event."),
    )
    duration_ms = models.PositiveIntegerField(
        _("duration (ms)"),
        null=True,
        blank=True,
        help_text=_("Duration of the detection in milliseconds."),
    )

    # --- Workflow ---------------------------------------------------------
    status = models.CharField(
        _("status"),
        max_length=20,
        choices=ReportStatus.choices,
        default=ReportStatus.PENDING,
        db_index=True,
    )

    # --- Notes ------------------------------------------------------------
    notes = models.TextField(
        _("notes"),
        blank=True,
        help_text=_("Operator notes or automatic processing remarks."),
    )

    class Meta:
        verbose_name = _("station report")
        verbose_name_plural = _("station reports")
        ordering = ["-recorded_at"]

    def __str__(self) -> str:
        device = self.camera or self.radio_receiver
        device_str = str(device) if device else _("unknown device")
        return f"{self.station.name} / {device_str} — {self.recorded_at:%Y-%m-%d %H:%M} UTC"


class ReportFile(TimeStampedModel):
    """
    Metadata for a data file associated with a StationReport.

    Describes a file that exists on the station's storage and can be
    requested for analysis.  The actual file content is not stored here.
    """

    report = models.ForeignKey(
        StationReport,
        on_delete=models.CASCADE,
        related_name="files",
        verbose_name=_("report"),
    )
    file_type = models.CharField(
        _("file type"),
        max_length=20,
        choices=FileType.choices,
        default=FileType.VIDEO,
        db_index=True,
    )
    filename = models.CharField(
        _("filename"),
        max_length=512,
        help_text=_("Original filename or path on the station storage."),
    )
    file_size_bytes = models.PositiveBigIntegerField(
        _("file size (bytes)"),
        null=True,
        blank=True,
        help_text=_("File size in bytes, if known."),
    )
    description = models.CharField(
        _("description"),
        max_length=255,
        blank=True,
        help_text=_("Short description of the file contents."),
    )
    is_available = models.BooleanField(
        _("available"),
        default=True,
        help_text=_("Whether this file can currently be requested or downloaded."),
    )

    class Meta:
        verbose_name = _("report file")
        verbose_name_plural = _("report files")
        ordering = ["file_type", "filename"]

    def __str__(self) -> str:
        return f"{self.get_file_type_display()} — {self.filename}"

    @property
    def file_size_display(self) -> str:
        """Human-readable file size."""
        if self.file_size_bytes is None:
            return "—"
        size = self.file_size_bytes
        for unit in ("B", "KB", "MB", "GB"):
            if size < 1024:
                return f"{size:.0f} {unit}"
            size /= 1024
        return f"{size:.1f} TB"


# ---------------------------------------------------------------------------
# Media requirements and attachments (station API)
# ---------------------------------------------------------------------------


class RequirementStatus(models.TextChoices):
    PENDING = "pending", _("Pending")
    FULFILLED = "fulfilled", _("Fulfilled")
    CANCELLED = "cancelled", _("Cancelled")


def _attachment_upload_to(instance: "ReportAttachment", filename: str) -> str:
    """Store uploaded attachments under media/attachments/{requirement_id}/{filename}."""
    import os  # noqa: PLC0415

    safe_name = os.path.basename(filename)
    return f"attachments/{instance.requirement_id}/{safe_name}"


class MediaRequirement(TimeStampedModel):
    """
    A request from an admin for specific local files from a station.

    The station script polls GET /api/v1/station/requirements/ to discover
    pending requirements, then fulfils each one by uploading the files via
    POST /api/v1/station/requirements/{id}/media/.

    When all ``requested_paths`` have been uploaded the status is
    automatically set to ``fulfilled``.
    """

    station = models.ForeignKey(
        Station,
        on_delete=models.CASCADE,
        related_name="media_requirements",
        verbose_name=_("station"),
    )
    requested_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="created_requirements",
        verbose_name=_("requested by"),
    )
    requested_paths = models.JSONField(
        _("requested paths"),
        default=list,
        help_text=_("List of local file paths on the station to be uploaded."),
    )
    status = models.CharField(
        _("status"),
        max_length=16,
        choices=RequirementStatus.choices,
        default=RequirementStatus.PENDING,
        db_index=True,
    )
    notes = models.TextField(
        _("notes"),
        blank=True,
        help_text=_("Admin notes about what these files are needed for."),
    )
    expires_at = models.DateTimeField(
        _("expires at"),
        null=True,
        blank=True,
        help_text=_("Optional deadline after which the requirement is no longer served to the script."),
    )

    class Meta:
        verbose_name = _("media requirement")
        verbose_name_plural = _("media requirements")
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"Requirement #{self.pk} [{self.status}] — {self.station.code}"


class ReportAttachment(TimeStampedModel):
    """
    A media file uploaded by a station script to fulfil a MediaRequirement.

    The actual file is written to Django MEDIA_ROOT; only metadata is stored
    in the remaining fields.
    """

    requirement = models.ForeignKey(
        MediaRequirement,
        on_delete=models.CASCADE,
        related_name="attachments",
        verbose_name=_("requirement"),
    )
    file = models.FileField(
        _("file"),
        upload_to=_attachment_upload_to,
        help_text=_("Uploaded media file from the station."),
    )
    original_path = models.CharField(
        _("original path"),
        max_length=1024,
        help_text=_("Local file path on the station storage."),
    )
    file_type = models.CharField(
        _("file type"),
        max_length=20,
        choices=FileType.choices,
        default=FileType.OTHER,
        db_index=True,
    )
    file_size_bytes = models.PositiveBigIntegerField(
        _("file size (bytes)"),
        null=True,
        blank=True,
    )
    uploaded_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="uploaded_attachments",
        verbose_name=_("uploaded by"),
    )

    class Meta:
        verbose_name = _("report attachment")
        verbose_name_plural = _("report attachments")
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"Attachment [{self.get_file_type_display()}] — {self.original_path}"
