# Generated by Django 5.1.8 on 2026-05-26 03:18

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNotice',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUIDv7 primary key — time-sortable unique identifier.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp when the record was last modified.', verbose_name='Updated at')),
                ('name', models.CharField(max_length=120, verbose_name='your name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('event_type', models.CharField(choices=[('meteor', 'Meteor'), ('fireball', 'Fireball / bolide'), ('aurora', 'Aurora'), ('satellite', 'Satellite / re-entry'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='event type')),
                ('observation_date', models.DateField(verbose_name='observation date')),
                ('location', models.CharField(help_text='City, region, or approximate coordinates', max_length=255, verbose_name='location')),
                ('description', models.TextField(help_text='Describe what you saw: direction, duration, brightness, colour…', max_length=2000, verbose_name='description')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_notices', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
            ],
            options={
                'verbose_name': 'event notice',
                'verbose_name_plural': 'event notices',
                'ordering': ['-created_at'],
            },
        ),
    ]
