# Generated by Django 5.1.8 on 2026-05-26 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnotice',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Astronomical event this notice was associated to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='events.astronomicalevent', verbose_name='linked event'),
        ),
    ]
