# Generated by Django 5.1.8 on 2026-05-26 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='owner',
            field=models.ForeignKey(help_text='User who owns and operates this station.', on_delete=django.db.models.deletion.PROTECT, related_name='stations', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['owner', 'status'], name='station_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['status'], name='station_status_idx'),
        ),
    ]
