# Generated by Django 5.1.8 on 2026-05-29 00:27

import sky_events.apps.station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_hash_ids_and_script_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="hash_id",
            field=models.CharField(
                default=sky_events.apps.station.models._generate_hash_id,
                editable=False,
                help_text="Short unique identifier used in script configuration files.",
                max_length=32,
                unique=True,
                verbose_name="Hash ID",
            ),
        ),
    ]
