# Generated by Django 5.1.8 on 2026-06-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0004_add_media_requirement_and_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="last_ping_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="UTC timestamp of the most recent heartbeat received from the station.",
                null=True,
                verbose_name="Last ping (UTC)",
            ),
        ),
    ]
