# Generated by Django 5.1.8 on 2026-05-26 03:25

import django.core.validators
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0002_initial'),
        ('radio', '0002_initial'),
        ('station', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AstronomicalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, help_text='UUIDv7 primary key — time-sortable unique identifier.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp when the record was last modified.', verbose_name='Updated at')),
                ('code', models.CharField(db_index=True, help_text='Unique admin-assigned identifier, e.g. SE-2026-001.', max_length=64, unique=True, verbose_name='event code')),
                ('name', models.CharField(help_text='Short human-readable name for the event.', max_length=255, verbose_name='name')),
                ('event_type', models.CharField(choices=[('meteor', 'Meteor'), ('fireball', 'Fireball / bolide'), ('aurora', 'Aurora'), ('satellite', 'Satellite / re-entry'), ('sporadic', 'Sporadic'), ('shower', 'Meteor shower'), ('other', 'Other')], db_index=True, default='meteor', max_length=20, verbose_name='event type')),
                ('status', models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('confirmed', 'Confirmed'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='unconfirmed', max_length=20, verbose_name='status')),
                ('detected_at', models.DateTimeField(db_index=True, help_text='UTC datetime when the event was observed.', verbose_name='detected at')),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Observed duration of the event in milliseconds.', null=True, verbose_name='duration (ms)')),
                ('peak_magnitude', models.DecimalField(blank=True, decimal_places=2, help_text='Peak apparent magnitude (negative = brighter).', max_digits=5, null=True, verbose_name='peak magnitude')),
                ('altitude_km', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated ablation altitude above sea level in km.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='altitude (km)')),
                ('velocity_km_s', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated geocentric entry velocity in km/s.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='velocity (km/s)')),
                ('description', models.TextField(blank=True, help_text='Public description of the event.', verbose_name='description')),
                ('notes', models.TextField(blank=True, help_text='Admin-only notes (not shown publicly).', verbose_name='internal notes')),
                ('cameras', models.ManyToManyField(blank=True, help_text='Cameras that recorded this event.', related_name='events', to='camera.camera', verbose_name='cameras')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('radio_receivers', models.ManyToManyField(blank=True, help_text='Radio receivers that detected an echo for this event.', related_name='events', to='radio.radioreceiver', verbose_name='radio receivers')),
                ('stations', models.ManyToManyField(blank=True, help_text='Stations that detected this event.', related_name='events', to='station.station', verbose_name='stations')),
            ],
            options={
                'verbose_name': 'astronomical event',
                'verbose_name_plural': 'astronomical events',
                'ordering': ['-detected_at'],
            },
        ),
    ]
