# Generated by Django 5.1.8 on 2026-05-28 23:28

import secrets

from django.db import migrations, models


def populate_script_tokens(apps, schema_editor):
    """Populate unique script_token for every existing User row."""
    User = apps.get_model("users", "User")
    for user in User.objects.filter(script_token=""):
        user.script_token = secrets.token_urlsafe(32)
        user.save(update_fields=["script_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        # Step 1 – add the column as nullable / no unique constraint
        migrations.AddField(
            model_name="user",
            name="script_token",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Unique secret token that the reporting script uses to authenticate. Never share this token publicly.",
                max_length=64,
                verbose_name="Script token",
            ),
            preserve_default=False,
        ),
        # Step 2 – fill in unique values for any pre-existing rows
        migrations.RunPython(populate_script_tokens, migrations.RunPython.noop),
        # Step 3 – add the unique constraint
        migrations.AlterField(
            model_name="user",
            name="script_token",
            field=models.CharField(
                default="",
                editable=False,
                help_text="Unique secret token that the reporting script uses to authenticate. Never share this token publicly.",
                max_length=64,
                unique=True,
                verbose_name="Script token",
            ),
        ),
    ]
